development:
  adapter: postgresql
  database: user_authdevelopment
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: user_authproduction
  pool: 5
  timeout: 5000
  url: <%=ENV['DATEBASE_URL']%>
